"""
Django settings for srpc_new project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from rest_framework.renderers import JSONRenderer
import pymysql
from dotenv import load_dotenv
import boto3
import json
from botocore.exceptions import ClientError
import time


def get_secret():
    secret_name = "rds!db-c5b1ec3f-90b0-44f2-8c26-d193d4411365"
    region_name = "us-east-1"

    client = boto3.client("secretsmanager", region_name=region_name)

    try:
        response = client.get_secret_value(SecretId=secret_name)
    except ClientError as e:
        raise e

    secret = json.loads(response["SecretString"])
    return secret



_secret_cache = None
_last_fetch = 0

def get_db_secret():
    global _secret_cache, _last_fetch

    if _secret_cache and time.time() - _last_fetch < 300:  # 5 min
        return _secret_cache

    _secret_cache = get_secret()
    _last_fetch = time.time()
    return _secret_cache

#load_dotenv() # Load environment variables from .env file in the current directory
load_dotenv("/home/ubuntu/.env") #production
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-@r_vhw8-vx^d8vbb89(jk7og4v)urz1zmw7zic@%)@(&qz%n*w'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#ALLOWED_HOSTS = ['*'] #loca test
ALLOWED_HOSTS = [ "uwmsrpc26.com",
    "uwmsrpc26.com",
    "api.uwmsrpc26.com",
    "dashboard.uwmsrpc26.com","127.0.0.1",
    "localhost",]
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}


# Application definition

INSTALLED_APPS = [
    'index',
    'insertgrade',
    'precheckposter',
    'home',
    'signin',
    'signup',
    'explearning',
    'threemt',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admindashboard', # Admin Dashboard
    'import_export', # Import Export
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'srpc_new.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'srpc_new.wsgi.application'

secret = get_db_secret()
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'SRPC2026',
        # 'USER': 'root',
        # 'PASSWORD': 'root1234',
        # 'HOST': 'localhost',
        'PORT': '3306',  # usually 3306 for MySQL
        
         'NAME': os.environ.get('DB_NAME'),
         'USER': os.environ.get('DB_USER'),
     #'PASSWORD': os.environ.get('DB_PASSWORD'), #for local testing
     'PASSWORD': secret['password'],
         'HOST': os.environ.get('DB_HOST'),
        'CONN_MAX_AGE': 60,
    }
}
# this is a general user root and any database can decide to give its access to root.
# CREATE USER 'root'@'%' IDENTIFIED BY 'divakar@Y123';


#giving all the privileges to the user root
# GRANT ALL PRIVILEGES ON SRPC2025.* TO 'root'@'%';

# FLUSH PRIVILEGES;

# Optional: Remove all previous migration files except __init__.py
# find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
# find . -path "*/migrations/*.pyc" -delete

AUTH_USER_MODEL = 'signup.User'


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#CORS_ORIGIN_ALLOW_ALL = True # for testing
CORS_ALLOWED_ORIGINS = [
    "https://uwmsrpc26.com",
    "https://dashboard.uwmsrpc26.com",
]

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://uwmsrpc26.com",
    "https://dashboard.uwmsrpc26.com",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True