# Generated by Django 4.1.7 on 2025-04-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total_Scores_Exp_Learning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("judged_count", models.IntegerField(default=0)),
                ("avg_reflection_score", models.FloatField(default=0)),
                ("avg_communication_score", models.FloatField(default=0)),
                ("avg_presentation_score", models.FloatField(default=0)),
                ("total_score", models.FloatField(default=0)),
                (
                    "poster_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.students"
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Scores Exp Learning",
                "verbose_name_plural": "Total Scores Exp Learning",
                "db_table": "total_scores_exp_learning",
            },
        ),
        migrations.CreateModel(
            name="ExpLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster_id", models.IntegerField(blank=True, null=True)),
                ("reflection_score", models.FloatField(blank=True, null=True)),
                ("communication_score", models.FloatField(blank=True, null=True)),
                ("presentation_score", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.students"
                    ),
                ),
            ],
        ),
    ]
