# Generated by Django 4.1.7 on 2025-04-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Total_Scores_ThreeMT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("judged_count", models.IntegerField(default=0)),
                ("avg_comprehension_content", models.FloatField(default=0)),
                ("avg_engagement", models.FloatField(default=0)),
                ("avg_communication", models.FloatField(default=0)),
                ("avg_overall_impression", models.FloatField(default=0)),
                ("total_score", models.FloatField(default=0)),
                (
                    "poster_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.students"
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Scores Three Minute Thesis",
                "verbose_name_plural": "Total Scores Three Minute Thesis",
                "db_table": "total_scores_three_mt",
            },
        ),
        migrations.CreateModel(
            name="ThreeMt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster_id", models.IntegerField(blank=True, null=True)),
                ("comprehension_content", models.FloatField(blank=True, null=True)),
                ("engagement", models.FloatField(blank=True, null=True)),
                ("communication", models.FloatField(blank=True, null=True)),
                ("overall_impression", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.students"
                    ),
                ),
            ],
        ),
    ]
