# Generated by Django 4.1.7 on 2025-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="poster_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
