# Generated by Django 4.1.7 on 2026-04-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_students_poster_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="dashboard_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
